"""Initial schema: corpus, chat, vector and full-text retrieval.

Written by hand rather than autogenerated. Autogenerate cannot infer the pgvector extension,
the German tsvector, the HNSW index, or the RLS policies — and those are precisely the parts
that make retrieval work.

Revision ID: 0001
Create Date: 2026-08-17
"""

from __future__ import annotations

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

EMBEDDING_DIMENSIONS = 768
FTS_CONFIG = "german"


def upgrade() -> None:
    op.execute("create extension if not exists vector")
    op.execute("create extension if not exists pgcrypto")

    op.create_table(
        "users",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.String(320), nullable=False, unique=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    op.create_table(
        "source_documents",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("doc_kind", sa.String(16), nullable=False),
        sa.Column("open_legal_data_id", sa.Integer, unique=True),
        sa.Column("court_name", sa.String(255)),
        sa.Column("court_id", sa.Integer),
        sa.Column("court_jurisdiction", sa.String(128)),
        sa.Column("decision_type", sa.String(64)),
        sa.Column("decision_date", sa.Date),
        sa.Column("published_date", sa.Date),
        sa.Column("decision_year", sa.Integer),
        sa.Column("file_number", sa.String(128)),
        sa.Column("ecli", sa.String(128)),
        sa.Column("source_url", sa.Text),
        sa.Column("markdown_content", sa.Text, nullable=False),
        sa.Column("norm_refs", sa.dialects.postgresql.JSONB, server_default="[]", nullable=False),
        sa.Column("revision_date", sa.Date),
        sa.Column("is_latest", sa.Boolean),
        sa.Column("license_note", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        # Not `file_number` alone: the Aktenzeichen is only unique within a court. '2 Ca 633/23'
        # is a perfectly ordinary number at many Arbeitsgerichte in the same year.
        sa.UniqueConstraint("court_id", "file_number", name="uq_source_documents_court_file"),
    )
    op.create_index("ix_source_documents_court_year", "source_documents", ["court_name", "decision_year"])
    op.create_index("ix_source_documents_doc_kind", "source_documents", ["doc_kind"])
    op.create_index("ix_source_documents_norm_refs", "source_documents", ["norm_refs"], postgresql_using="gin")

    op.create_table(
        "document_chunks",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("document_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("source_documents.id", ondelete="CASCADE"), nullable=False),
        sa.Column("chunk_index", sa.Integer, nullable=False),
        sa.Column("section", sa.String(128)),
        sa.Column("paragraph_number", sa.Integer),
        sa.Column("text", sa.Text, nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.Vector(EMBEDDING_DIMENSIONS)),
        sa.Column(
            "text_search",
            sa.dialects.postgresql.TSVECTOR,
            sa.Computed(f"to_tsvector('{FTS_CONFIG}', text)", persisted=True),
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("document_id", "chunk_index", name="uq_document_chunks_doc_index"),
    )
    # Cosine, matching how e5 embeddings are compared. Distance operator and index opclass
    # must agree or the index is silently ignored and every query becomes a seq scan.
    op.execute(
        "create index ix_document_chunks_embedding on document_chunks "
        "using hnsw (embedding vector_cosine_ops)"
    )
    op.create_index("ix_document_chunks_text_search", "document_chunks", ["text_search"], postgresql_using="gin")
    op.create_index("ix_document_chunks_document", "document_chunks", ["document_id"])

    op.create_table(
        "chat_threads",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("title", sa.String(255)),
        sa.Column("answer_language", sa.String(2), server_default="de", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_chat_threads_user", "chat_threads", ["user_id", "updated_at"])

    op.create_table(
        "chat_messages",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("thread_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("chat_threads.id", ondelete="CASCADE"), nullable=False),
        sa.Column("role", sa.String(16), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("translated_query", sa.Text),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_chat_messages_thread", "chat_messages", ["thread_id", "created_at"])

    op.create_table(
        "message_citations",
        sa.Column("id", sa.dialects.postgresql.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("message_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("chat_messages.id", ondelete="CASCADE"), nullable=False),
        sa.Column("chunk_id", sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey("document_chunks.id", ondelete="CASCADE"), nullable=False),
        sa.Column("rank", sa.Integer, nullable=False),
        sa.Column("quoted_text", sa.Text),
        sa.Column("scores", sa.dialects.postgresql.JSONB, server_default="{}", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_message_citations_message", "message_citations", ["message_id", "rank"])

    # --- Row level security -------------------------------------------------------------
    # The corpus is public domain and readable by anyone signed in. Threads, messages and
    # citations are private to their owner. `auth.uid()` is Supabase's verified JWT subject;
    # it cannot be spoofed from the request body.
    op.execute("alter table chat_threads enable row level security")
    op.execute("alter table chat_messages enable row level security")
    op.execute("alter table message_citations enable row level security")
    op.execute("alter table source_documents enable row level security")
    op.execute("alter table document_chunks enable row level security")

    op.execute(
        "create policy source_documents_read on source_documents for select "
        "to authenticated using (true)"
    )
    op.execute(
        "create policy document_chunks_read on document_chunks for select "
        "to authenticated using (true)"
    )
    op.execute(
        "create policy chat_threads_own on chat_threads for all "
        "to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())"
    )
    op.execute(
        "create policy chat_messages_own on chat_messages for all to authenticated "
        "using (exists (select 1 from chat_threads t where t.id = thread_id and t.user_id = auth.uid())) "
        "with check (exists (select 1 from chat_threads t where t.id = thread_id and t.user_id = auth.uid()))"
    )
    op.execute(
        "create policy message_citations_own on message_citations for all to authenticated "
        "using (exists (select 1 from chat_messages m join chat_threads t on t.id = m.thread_id "
        "where m.id = message_id and t.user_id = auth.uid())) "
        "with check (exists (select 1 from chat_messages m join chat_threads t on t.id = m.thread_id "
        "where m.id = message_id and t.user_id = auth.uid()))"
    )


def downgrade() -> None:
    op.drop_table("message_citations")
    op.drop_table("chat_messages")
    op.drop_table("chat_threads")
    op.drop_table("document_chunks")
    op.drop_table("source_documents")
    op.drop_table("users")
